version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    env_file: .env
    environment:
        POSTGRES_USER: ${POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - 127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 3s
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  rabbitmq:
    image: rabbitmq:3.8-alpine
    restart: always
    env_file: .env
    environment:
      RABBITMQ_DEFAULT_USER: ${MQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${MQ_PASSWORD}
    ports:
      - 127.0.0.1:${MQ_PORT}:${MQ_PORT}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  redis:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file: .env
    environment:
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        REDIS_DATABASE: ${REDIS_DB_NAME}
    ports:
      - 127.0.0.1:${REDIS_PORT}:${REDIS_PORT}
    healthcheck:
      test: redis-cli -a ${REDIS_PASSWORD} ping | grep PONG
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 3s
    volumes:
      - redis_data:/root/redis
      - redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  postgres-data:
  redis_data:
  redis.conf:
