"""Del category_id in product and brandname.

Revision ID: 18202417a783
Revises: c8e11dfe4de2
Create Date: 2024-05-27 16:44:16.542777

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18202417a783"
down_revision: Union[str, None] = "c8e11dfe4de2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_products_manually_filled_specification_brandname",
        table_name="manually_filled_specification",
        schema="products",
    )
    op.drop_column("manually_filled_specification", "brandname", schema="products")
    op.drop_constraint("product_category_id_fkey", "product", schema="products", type_="foreignkey")
    op.drop_column("product", "category_id", schema="products")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("category_id", sa.UUID(), autoincrement=False, nullable=True), schema="products")
    op.create_foreign_key(
        "product_category_id_fkey",
        "product",
        "category",
        ["category_id"],
        ["id"],
        source_schema="products",
        referent_schema="products",
        ondelete="SET NULL",
    )
    op.add_column(
        "manually_filled_specification",
        sa.Column("brandname", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        schema="products",
    )
    op.create_index(
        "ix_products_manually_filled_specification_brandname",
        "manually_filled_specification",
        ["brandname"],
        unique=False,
        schema="products",
    )
    # ### end Alembic commands ###
