"""add product status column

Revision ID: 2bd835447ad8
Revises: 5813fa1df89b
Create Date: 2024-06-03 10:31:55.971819

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2bd835447ad8"
down_revision: Union[str, None] = "3a6fb8b03b28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

product_statuses = ("new", "on_moderation", "ready_for_sale", "on_sale", "needs_fix", "not_for_sale", "deleted")
new_type = sa.Enum(*product_statuses, name="product_status_enum", schema="products")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    new_type.create(op.get_bind(), checkfirst=False)
    op.add_column("product", sa.Column("status", new_type, nullable=False, server_default="new"), schema="products")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "status", schema="products")
    op.execute("DROP TYPE products.product_status_enum")
    # ### end Alembic commands ###
