"""Correct document model

Revision ID: 3a6fb8b03b28
Revises: 5813fa1df89b
Create Date: 2024-06-10 13:22:00.462064

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a6fb8b03b28"
down_revision: Union[str, None] = "5813fa1df89b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document", sa.Column("key", sa.String(), nullable=False), schema="products")
    op.add_column("document", sa.Column("name", sa.String(), nullable=False), schema="products")
    op.add_column("document", sa.Column("extension", sa.String(), nullable=False), schema="products")
    op.drop_column("document", "url", schema="products")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document", sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False), schema="products")
    op.drop_column("document", "extension", schema="products")
    op.drop_column("document", "name", schema="products")
    op.drop_column("document", "key", schema="products")
    # ### end Alembic commands ###
