"""empty message

Revision ID: 5813fa1df89b
Revises: 18202417a783
Create Date: 2024-06-02 18:32:33.514321

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5813fa1df89b"
down_revision: Union[str, None] = "18202417a783"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message",
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.product.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="products",
    )
    op.create_index(op.f("ix_products_message_id"), "message", ["id"], unique=True, schema="products")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_message_id"), table_name="message", schema="products")
    op.drop_table("message", schema="products")
    # ### end Alembic commands ###
