"""len_128_product_name

Revision ID: c8e11dfe4de2
Revises: cbca7bcad4db
Create Date: 2024-05-24 00:21:14.735247

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8e11dfe4de2"
down_revision: Union[str, None] = "cbca7bcad4db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product",
        "name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=128),
        existing_nullable=False,
        schema="products",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product",
        "name",
        existing_type=sa.String(length=128),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
        schema="products",
    )
    # ### end Alembic commands ###
