name: Run pytest

on:
  push:
    branches:
      - '**'

jobs:

  lint:
    name: Check the code with python linters
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: github_actions
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

      redis:
        image: redis:latest
        ports:
          - "6379:6379"

    env:
      TEST_DATABASE_HOST: db_test
      TEST_DATABASE_USERNAME: postgres
      TEST_DATABASE_PASSWORD: postgres
      TEST_DATABASE_PORT: 5432
      TEST_DATABASE_NAME: postgres
      TEST_REDIS_DB_NAME: redis
      TEST_REDIS_HOST: redis
      TEST_REDIS_PORT: 6379

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          poetry config virtualenvs.in-project true
          poetry install
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
      - name: Run Tests
        run: |
          pytest --cov --cov-report=xml          
